### PR TITLE
make send_event also pass EventData through to conditions

### PR DESCRIPTION
**Pull request by acjc**
Hey,

I've recently found that it would be useful if condition functions also had access to EventData (or args/kwargs) so that data can be passed through when triggering a transition to help determine whether the transition should succeed or not.

Here's a PR implementing this feature. Would appreciate it if you could take a look, thanks!

### CODE REVIEW

**Comment by tyarkoni** [comment]
Thanks for the PR, @acjc! I think this an excellent idea, and I'm looking forward to merging it, but it may be a couple of days before I get to it, as I'm swamped with other stuff.

**Comment by acjc** [comment]
No problem, thanks for getting back to me :)

**Comment by tyarkoni** [comment]
Looks great, thanks!

**Comment by acjc** [comment]
Thanks for merging, would you mind doing a new pip release?

**Comment by tyarkoni** [comment]
Yep, done!

**Pull request merged**
