### PR TITLE
Fixing double circle on first state

### PR DESCRIPTION
**Pull request by wtgee**
Small fix for identifying the first state.

### CODE REVIEW

**Comment by wtgee** [comment]
Sorry, I'm not sure what happened. I tried to do two separate PR and the first one built fine as it's pretty simple, but I think the second PR merged with it. How do I find out where travis-cl failed?

**Comment by tyarkoni** [comment]
Click on "details" under the build failure:

https://travis-ci.org/tyarkoni/transitions/jobs/100266582

Not sure why it's failing as a result of your changes, but the test itself could use some improvement (right now it hardcodes the removal of the 'C' state). I'll look at it later this week if you don't get to it first.

**Comment by wtgee** [comment]
Thanks, I got it figured out (logging in helps).

The build is failing on the test for the nested graphs (HSM). I wanted to
play with those this week anyway so I'll see what I can do.

Thanks,

On Mon, Jan 4, 2016 at 6:16 PM, Tal Yarkoni <notifications@github.com>
wrote:

> Click on "details" under the build failure:
>
> https://travis-ci.org/tyarkoni/transitions/jobs/100266582
>
> Not sure why it's failing as a result of your changes, but the test itself
> could use some improvement (right now it hardcodes the removal of the 'C'
> state). I'll look at it later this week if you don't get to it first.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tyarkoni/transitions/pull/56#issuecomment-168891724>.
>



-- 
~Wilfred Tyler Gee

**Comment by aleneum** [comment]
Hi,

I also fiddled around with the diagram and doublecircle but went for `self.machine._initial directly`. I also prefer the idea of an additional argument in the `_add_nodes` method because it does not require to access protected attributes. Since `_add_nodes` is overwritten in `AAGraph` in extension.py. It should be added there too. This could also be used to mark the initial states of nested states. I would not pass it via `get_graph ` but but let the machine pass it because the initial state was already declared in `__init__`. 

`self.assertEqual(set(m.states.keys()) - set('C'), node_names)` does work for me though.

**Comment by tyarkoni** [comment]
Is this ready to merge, @wtgee?

**Comment by wtgee** [comment]
Yes, it should be.  You'll get a merge conflict with @aleneum work on the double-circle but it should be easy to resolve. A fix for the graph title is also included.

**Comment by tyarkoni** [comment]
Done! Thanks!

**Pull request merged**
