### PR TITLE
Tox

### PR DESCRIPTION
**Pull request by aisbaa**
Hi, I've added support for [tox](https://tox.readthedocs.io/en/latest/). Should help testing transitions with many interpreters on local machine.

### CODE REVIEW

**Comment by tyarkoni** [comment]
Thanks for the PR, @aisbaa. Could you provide a quick summary of the concrete benefits? I'm not familiar with tox, and will look at the docs when I have a chance, but I'm kind of swamped at the moment. It's not immediately obvious to me what we gain over the current setup. (Just to be clear, I'm not expressing any skepticism about the benefits, I just don't have the time to look into it right now. @aleneum or @wtgee may have a more informed opinion.)

**Comment by aisbaa** [comment]
Will try to do my best. Basically tox tries to minimize differences between all testing environments by providing really strict isolation from system.

1. It creates separate virtualenv for each interpreter (missing interpreter can be skipped). By running tox you would be running tests on all available python interpreters.
2. Virtualenv does not include system libraries (unless configured to include) - therefore there is less of a chance that tests run on someones computer and don't run on other because of dependency misconfiguration.
3. Before running tests it installs latest version of your library into virtualenv, so setup.py gets tested.

Hope this helps!

**Comment by aleneum** [comment]
That does sound interesting and I already have a project in mind where I definitely will try it out :).
Regarding transitions/github I'd say that most of the functionality tox offers is already covered with travis. I might be wrong though.

**Comment by aisbaa** [comment]
@aleneum yes indeed most is already covered by travis, will close this pull request ;)

**Pull request closed without merging**
