### PR TITLE
doc: Improve info about callback execution order

### PR DESCRIPTION
**Pull request by ankostis**
The bullets in the README where explained the order of *some* of the callbacks were very helpful, 
but I had to read the code to be sure about the other callbacks involved.
Therefor I made the following enhancements to its contents:

- Converted into a table.
- Promoted as a new section in the contents.
- Added status enter/exit Cbs,;
- Added machine default before/after
- Add section in contents.
- Format as table.

### CODE REVIEW

**Comment by ankostis** [comment]
I realized i did not pushed over master but on top of dev-0.4.4.  
If it is a problem, I can rebase.

**Comment by aleneum** [comment]
Hello @ankostis,

thank you for your input. A pull request into `dev-0.4` would be much appreciated since I still have minor things to do before merging 0.4 into master.

best regards,
Alex

**Comment by ankostis** [comment]
You mean I should rebase on `master`, correct?

**Comment by aleneum** [comment]
Both is okay, 

we can add your changes to dev-0.4 or you rebase it and we merge in into master.

I see, already done. Thank you for clarifying this part of the documentation.

**Comment by ankostis** [comment]
Please check if my ordering is correct.

**Comment by aleneum** [comment]
Will be done.

**Pull request merged**
